[package]
name = "ctr"
description = "ctr is a cute companion for your system."
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/drgndk/ctr"
edition = "2024"

[dependencies]
std_v2 = { path = "./crates/std_v2" }
common = { path = "./crates/common" }

clap = { version = "~4.5.28", features = ["derive"] }
