[package]
name = "operation_derive"
edition = "2024"

[dependencies]
syn = "~1.0"
quote = "~1.0.38"
proc-macro2 = "~1.0.93"

common = { path = "../common" }

[lib]
proc-macro = true
path = "src/lib.rs"
