[package]
name = "common"
edition = "2024"

[dependencies]
paste = "~1.0.15"
levenshtein = "~1.0.5"
serde = { version = "~1.0.217", features = ["derive"] }
clap_complete_command = { version = "~0.6.1" }
dirs = "~6.0.0"

[lib]
path = "src/lib.rs"
